server:
  port: 8083

spring:
  application:
    name: regular-cards

regular:
  executeUrl: http://something.org/regular/execute
  path: /home/anastasia/Work/projects/reactor-nastia/tools/regulars.txt
